# Анализ лояльности пользователей Яндекс Афиш

## Цели и задачи проекта:
С помощью датасета с информацией о клиентах и их активности, надо проанализировать и выявить портрет пользователя, который с большей вероятностью будет возвращаться на платформу и делать повторные заказы. Это поможет оптимизировать рекламные бюжеты и влиять на продолжительность удержания клиента

## Данные:
Выгрузка из базы данных SQL должна позволить собрать следующие данные:

- user_id — уникальный идентификатор пользователя, совершившего заказ;
- device_type_canonical — тип устройства, с которого был оформлен заказ (mobile — мобильные устройства, desktop — стационарные);
- order_id — уникальный идентификатор заказа;
- order_dt — дата создания заказа (используйте данные created_dt_msk);
- order_ts — дата и время создания заказа (используйте данные created_ts_msk);
- currency_code — валюта оплаты;
- revenue — выручка от заказа;
- tickets_count — количество купленных билетов;
- days_since_prev — количество дней от предыдущей покупки пользователя, для пользователей с одной покупкой — значение пропущено;
- event_id — уникальный идентификатор мероприятия;
- service_name — название билетного оператора;
- event_type_main — основной тип мероприятия (театральная постановка, концерт и так далее);
- region_name — название региона, в котором прошло мероприятие;
- city_name — название города, в котором прошло мероприятие.

### 1. Загрузка данных и сбор общей информации

In [1]:
#Установка необходимых библиотек
!pip install phik

Requirement already satisfied: phik in /opt/anaconda3/lib/python3.13/site-packages (0.12.5)
Requirement already satisfied: numpy>=1.18.0 in /opt/anaconda3/lib/python3.13/site-packages (from phik) (2.3.5)
Requirement already satisfied: scipy>=1.5.2 in /opt/anaconda3/lib/python3.13/site-packages (from phik) (1.16.3)
Requirement already satisfied: pandas>=0.25.1 in /opt/anaconda3/lib/python3.13/site-packages (from phik) (2.3.3)
Requirement already satisfied: matplotlib>=2.2.3 in /opt/anaconda3/lib/python3.13/site-packages (from phik) (3.10.6)
Requirement already satisfied: joblib>=0.14.1 in /opt/anaconda3/lib/python3.13/site-packages (from phik) (1.5.2)
Requirement already satisfied: contourpy>=1.0.1 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib>=2.2.3->phik) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib>=2.2.3->phik) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib>=2.2.3->phik) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib>=2.2.3->phik) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib>=2.2.3->phik) (25.0)
Requirement already satisfied: pillow>=8 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib>=2.2.3->phik) (12.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib>=2.2.3->phik) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in /opt/anaconda3/lib/python3.13/site-packages (from matplotlib>=2.2.3->phik) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas>=0.25.1->phik) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas>=0.25.1->phik) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.7->matplotlib>=2.2.3->phik) (1.17.0)

In [2]:
!pip install sqlalchemy

Requirement already satisfied: sqlalchemy in /opt/anaconda3/lib/python3.13/site-packages (2.0.43)
Requirement already satisfied: typing-extensions>=4.6.0 in /opt/anaconda3/lib/python3.13/site-packages (from sqlalchemy) (4.15.0)

In [3]:
!pip install psycopg2

Requirement already satisfied: psycopg2 in /opt/anaconda3/lib/python3.13/site-packages (2.9.12)

In [4]:
#Импорт необходимых библиотек для анализа данных
import pandas as pd
import numpy as np

#Импорт библиотек для визуализации
import matplotlib.pyplot as plt
import seaborn as sns

#Импорт внутрненних библиотек для работы с чувствительными файлами
import os
import dotenv
from sqlalchemy import create_engine

In [5]:
#Подгружаю данные с доступом к БД через .env-файл
db_config = {
    'user': os.getenv('DB_USER'),
    'pwd': os.getenv('DB_PASSWORD'), # пароль
    'host': os.getenv('DB_HOST'),
    'port': os.getenv('DB_PORT'), # порт подключения
    'db': os.getenv('DB_NAME')
}

In [6]:
#Импортирую строку для подключения
connection_string = 'postgresql://{}:{}@{}:{}/{}'.format(
    db_config['user'],
    db_config['pwd'],
    db_config['host'],
    db_config['port'],
    db_config['db'],
)

In [7]:
#Создаем соединение с БД
engine = create_engine(connection_string)

In [8]:
#Проверяю подключение к БД
db_config

{'user': 'praktikum_student',
 'pwd': 'Sdf4$2;d-d30pp',
 'host': 'rc1b-wcoijxj3yxfsf3fs.mdb.yandexcloud.net',
 'port': '6432',
 'db': 'data-analyst-afisha'}

In [9]:
#Выгружаем данные из БД с помощью SQL-запроса
query = '''
-- Настройка параметра synchronize_seqscans важна для проверки
WITH set_config_precode AS (
  SELECT set_config('synchronize_seqscans', 'off', true)
)
-- Напишите ваш запрос ниже
SELECT p.user_id,
      p.device_type_canonical,
      p.order_id,
      p.created_dt_msk AS order_dt,
      p.created_ts_msk AS order_ts,
      p.currency_code,
      p.revenue,
      p.tickets_count,
      EXTRACT (DAY FROM (p.created_dt_msk - LAG(p.created_dt_msk) OVER (PARTITION BY p.user_id ORDER BY p.created_dt_msk)))::INTEGER AS days_since_prev,
      p.event_id,
      e.event_name_code AS event_name,
      e.event_type_main,
      p.service_name,
      r.region_name,
      c.city_name
FROM afisha.purchases p
JOIN afisha.events e USING(event_id)
JOIN afisha.city c USING(city_id)
JOIN afisha.regions r USING(region_id)
WHERE p.device_type_canonical IN ('mobile', 'desktop') AND e.event_type_main NOT IN ('фильм')
ORDER BY p.user_id;
'''

In [10]:
#Присваиваем то что извлекаем из БД переменной
df = pd.read_sql_query(query, con=engine)

In [11]:
#Проверяю результат выгрузки из БД
df.head(3)

,user_id,device_type_canonical,order_id,order_dt,order_ts,currency_code,revenue,tickets_count,days_since_prev,event_id,event_name,event_type_main,service_name,region_name,city_name
0,0002849b70a3ce2,mobile,4359165,2024-08-20,2024-08-20 16:08:03,rub,1521.94,4,NaN,169230,f0f7b271-04eb-4af6-bcb8-8f05cf46d6ad,театр,Край билетов,Каменевский регион,Глиногорск
1,0005ca5e93f2cf4,mobile,7965605,2024-07-23,2024-07-23 18:36:24,rub,289.45,2,NaN,237325,40efeb04-81b7-4135-b41f-708ff00cc64c,выставки,Мой билет,Каменевский регион,Глиногорск
2,0005ca5e93f2cf4,mobile,7292370,2024-10-06,2024-10-06 13:56:02,rub,1258.57,4,75.0,578454,01f3fb7b-ed07-4f94-b1d3-9a2e1ee5a8ca,другое,За билетом!,Каменевский регион,Глиногорск

In [12]:
#Проверяю размер датасета
df.shape

(290611, 15)

In [13]:
#Проверяю выгрузку колонок
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 290611 entries, 0 to 290610
Data columns (total 15 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   user_id                290611 non-null  object
 1   device_type_canonical  290611 non-null  object
 2   order_id               290611 non-null  int64
 3   order_dt               290611 non-null  datetime64[ns]
 4   order_ts               290611 non-null  datetime64[ns]
 5   currency_code          290611 non-null  object
 6   revenue                290611 non-null  float64
 7   tickets_count          290611 non-null  int64
 8   days_since_prev        268678 non-null  float64
 9   event_id               290611 non-null  int64
 10  event_name             290611 non-null  object
 11  event_type_main        290611 non-null  object
 12  service_name           290611 non-null  object
 13  region_name            290611 non-null  object
 14  city_name              290611 non-null  object
dtypes: datetime64[ns](2), float64(2), int64(3), object(8)
memory usage: 33.3+ MB

##### Промежуточный вывод по шагу 1 (Загрузка и сбор общей информации о датасте):

- 1. Данные выгрузились корректно
- 2. На первый взгляд данные соответствуют своим типам в колонках
- 3. Вижу явно пропущенные значения только в колонке "days_since_prev"
- 4. Названия колонок приведены к одному типу
- 5. Размерность колонок с целочисленными показателями можно уменьшить

### 2. Предобработка данных

Задача 2.1. Данные о выручке сервиса представлены в российских рублях и казахстанских тенге. Приведите выручку к единой валюте — российскому рублю.

In [14]:
#Подгружаю датасет с информацией о курсе валют в переменную
df_kzt = pd.read_csv('final_tickets_tenge_df.csv')

In [15]:
#Проверяю результат выгрузки
df_kzt.head(3)

         data  nominal     curs  cdx
0  2024-01-10      100  19.9391  kzt
1  2024-01-11      100  19.7255  kzt
2  2024-01-12      100  19.5839  kzt

In [16]:
#Смотрю на типы колонок 
df_kzt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 357 entries, 0 to 356
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   data     357 non-null    object
 1   nominal  357 non-null    int64
 2   curs     357 non-null    float64
 3   cdx      357 non-null    object
dtypes: float64(1), int64(1), object(2)
memory usage: 11.3+ KB

Идея простая, соединим 2 датасета с помощью left-join (Левая таблица - df, правая df_kzt)

In [17]:
#Преобразовываю тип data, чтобы правильно соединить таблицы
df_kzt['data'] = pd.to_datetime(df_kzt['data'])

In [18]:
#Проверяю результат преобразования типов
df_kzt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 357 entries, 0 to 356
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   data     357 non-null    datetime64[ns]
 1   nominal  357 non-null    int64
 2   curs     357 non-null    float64
 3   cdx      357 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(1), object(1)
memory usage: 11.3+ KB

In [19]:
#Соединяю таблицы
df = df.merge(df_kzt[['data', 'curs']], left_on='order_dt', right_on='data', how='left').drop('data', axis=1)

In [20]:
#Проверяю результат
df.head(5)

,user_id,device_type_canonical,order_id,order_dt,order_ts,currency_code,revenue,tickets_count,days_since_prev,event_id,event_name,event_type_main,service_name,region_name,city_name,curs
0,0002849b70a3ce2,mobile,4359165,2024-08-20,2024-08-20 16:08:03,rub,1521.94,4,NaN,169230,f0f7b271-04eb-4af6-bcb8-8f05cf46d6ad,театр,Край билетов,Каменевский регион,Глиногорск,18.6972
1,0005ca5e93f2cf4,mobile,7965605,2024-07-23,2024-07-23 18:36:24,rub,289.45,2,NaN,237325,40efeb04-81b7-4135-b41f-708ff00cc64c,выставки,Мой билет,Каменевский регион,Глиногорск,18.3419
2,0005ca5e93f2cf4,mobile,7292370,2024-10-06,2024-10-06 13:56:02,rub,1258.57,4,75.0,578454,01f3fb7b-ed07-4f94-b1d3-9a2e1ee5a8ca,другое,За билетом!,Каменевский регион,Глиногорск,19.6475
3,000898990054619,mobile,1139875,2024-07-13,2024-07-13 19:40:48,rub,8.49,2,NaN,387271,2f638715-8844-466c-b43f-378a627c419f,другое,Лови билет!,Североярская область,Озёрск,18.5010
4,000898990054619,mobile,972400,2024-10-04,2024-10-04 22:33:15,rub,1390.41,3,83.0,509453,10d805d3-9809-4d8a-834e-225b7d03f95d,стендап,Билеты без проблем,Озернинский край,Родниковецк,19.6648

In [25]:
#Теперь делаем перерасчет выручки только для тех колонок, где валюта казахский тенге
df['revenue_rub'] = df['revenue'].where(df['currency_code'] == 'rub', df['revenue'] * df['curs'] / 100)

In [26]:
#Проверяю результат
df[df['currency_code'] == 'kzt']

,user_id,device_type_canonical,order_id,order_dt,order_ts,currency_code,revenue,tickets_count,days_since_prev,event_id,event_name,event_type_main,service_name,region_name,city_name,curs,revenue_rub
70,0033403583a55ed,mobile,7850214,2024-09-17,2024-09-17 16:52:06,kzt,518.10,4,20.0,559919,f5ec2467-ee48-42f3-89a0-a2d90d1d6fce,другое,Билеты без проблем,Верхоречная область,Серебрянка,19.0125,98.503762
89,0040e12d70fae81,desktop,8634925,2024-09-02,2024-09-02 19:49:14,kzt,347.18,3,39.0,559476,61ec7c0e-ea0c-4a3e-a63a-09cbe1bc6177,другое,Билеты без проблем,Верхоречная область,Серебрянка,18.9330,65.731589
96,0054b38b2653e6e,mobile,7625522,2024-09-09,2024-09-09 18:06:04,kzt,328.77,4,NaN,559582,524f434e-0381-4f47-9688-7c4e41961b65,другое,Билеты без проблем,Верхоречная область,Серебрянка,18.5991,61.148261
277,00f4f5244501ce6,mobile,720419,2024-06-11,2024-06-11 20:15:57,kzt,22021.55,5,NaN,536826,76af4f88-c554-4e9e-9df4-1cc8aeec8959,концерты,Мой билет,Верхоречная область,Серебрянка,19.8928,4380.702898
460,01370a0e9c1a7d5,desktop,5227657,2024-06-04,2024-06-04 13:28:17,kzt,7397.66,4,1.0,533803,0686ac7b-6f3e-4177-bb73-16b54acd1223,концерты,Мой билет,Шанырский регион,Широковка,19.9833,1478.296591
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
290484,ffc24188a1d58f2,mobile,6862648,2024-07-11,2024-07-11 12:39:48,kzt,4735.52,2,20.0,538828,603c97c6-b64f-4ec6-8de9-20b95c20b2b5,концерты,Билеты без проблем,Верхоречная область,Серебрянка,18.2738,865.359454
290485,ffc24188a1d58f2,mobile,6763294,2024-09-05,2024-09-05 12:07:00,kzt,4735.52,2,56.0,538828,603c97c6-b64f-4ec6-8de9-20b95c20b2b5,концерты,Билеты без проблем,Верхоречная область,Серебрянка,18.4217,872.363288
290486,ffc24188a1d58f2,mobile,3984021,2024-09-06,2024-09-06 19:20:03,kzt,1849.41,1,1.0,533803,0686ac7b-6f3e-4177-bb73-16b54acd1223,концерты,Мой билет,Шанырский регион,Широковка,18.5504,343.072953
290488,ffc4133fbba20f4,mobile,8493898,2024-06-21,2024-06-21 13:41:39,kzt,3698.83,2,NaN,533803,0686ac7b-6f3e-4177-bb73-16b54acd1223,концерты,Мой билет,Шанырский регион,Широковка,18.5791,687.209325
290489,ffc4133fbba20f4,mobile,8493869,2024-06-21,2024-06-21 14:04:34,kzt,3698.83,2,0.0,533803,0686ac7b-6f3e-4177-bb73-16b54acd1223,концерты,Мой билет,Шанырский регион,Широковка,18.5791,687.209325

**Промежуточный итог по заданию 2.1:**
Была создана новая колонка c перерасчитанной выручкой из казахского тенге в рубли

##### Задача 2.2. Пропущенные значение и преобразование колонок

In [28]:
#Смотрю на количество пропусков в колонках
df.isna().sum()

user_id                      0
device_type_canonical        0
order_id                     0
order_dt                     0
order_ts                     0
currency_code                0
revenue                      0
tickets_count                0
days_since_prev          21933
event_id                     0
event_name                   0
event_type_main              0
service_name                 0
region_name                  0
city_name                    0
curs                         0
revenue_rub                  0
dtype: int64

In [30]:
#Изучим природу пропусков
df[df['days_since_prev'].isna()].head()

,user_id,device_type_canonical,order_id,order_dt,order_ts,currency_code,revenue,tickets_count,days_since_prev,event_id,event_name,event_type_main,service_name,region_name,city_name,curs,revenue_rub
0,0002849b70a3ce2,mobile,4359165,2024-08-20,2024-08-20 16:08:03,rub,1521.94,4,NaN,169230,f0f7b271-04eb-4af6-bcb8-8f05cf46d6ad,театр,Край билетов,Каменевский регион,Глиногорск,18.6972,1521.94
1,0005ca5e93f2cf4,mobile,7965605,2024-07-23,2024-07-23 18:36:24,rub,289.45,2,NaN,237325,40efeb04-81b7-4135-b41f-708ff00cc64c,выставки,Мой билет,Каменевский регион,Глиногорск,18.3419,289.45
3,000898990054619,mobile,1139875,2024-07-13,2024-07-13 19:40:48,rub,8.49,2,NaN,387271,2f638715-8844-466c-b43f-378a627c419f,другое,Лови билет!,Североярская область,Озёрск,18.5010,8.49
6,00096d1f542ab2b,desktop,6636941,2024-08-15,2024-08-15 16:48:48,rub,917.83,4,NaN,201953,2f98d69f-4e60-4ffc-8f16-e539383526b1,театр,Край билетов,Каменевский регион,Глиногорск,18.7730,917.83
7,000a55a418c128c,mobile,4657981,2024-09-29,2024-09-29 19:39:12,rub,47.78,1,NaN,265857,0d876e01-851e-458b-ba61-753e0e0c4063,театр,Лучшие билеты,Поленовский край,Дальнозолотск,19.3741,47.78

**Промежуточный итог по заданию 2.2:**
Было выявлено, что пропуски в колонке "days_since_prev" связаны с тем, что у клиентов просто нету повторных покупок, соответственно и временной разницы между покупками посчитать нельзя

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 290611 entries, 0 to 290610
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   user_id                290611 non-null  object
 1   device_type_canonical  290611 non-null  object
 2   order_id               290611 non-null  int64
 3   order_dt               290611 non-null  datetime64[ns]
 4   order_ts               290611 non-null  datetime64[ns]
 5   currency_code          290611 non-null  object
 6   revenue                290611 non-null  float64
 7   tickets_count          290611 non-null  int64
 8   days_since_prev        268678 non-null  float64
 9   event_id               290611 non-null  int64
 10  event_name             290611 non-null  object
 11  event_type_main        290611 non-null  object
 12  service_name           290611 non-null  object
 13  region_name            290611 non-null  object
 14  city_name              290611 non-null  object
 15  curs                   290611 non-null  float64
 16  revenue_rub            290611 non-null  float64
dtypes: datetime64[ns](2), float64(4), int64(3), object(8)
memory usage: 37.7+ MB

In [39]:
#Создаю список колонок с целочисленными данными
columns=['order_id', 'tickets_count', 'event_id']

In [40]:
#Уменьшаем размерность с помощью цикла
for column in columns:
    df[column] = pd.to_numeric(df[column], downcast='integer')

In [41]:
#Проверяю результат
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 290611 entries, 0 to 290610
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   user_id                290611 non-null  object
 1   device_type_canonical  290611 non-null  object
 2   order_id               290611 non-null  int32
 3   order_dt               290611 non-null  datetime64[ns]
 4   order_ts               290611 non-null  datetime64[ns]
 5   currency_code          290611 non-null  object
 6   revenue                290611 non-null  float64
 7   tickets_count          290611 non-null  int8
 8   days_since_prev        268678 non-null  float64
 9   event_id               290611 non-null  int32
 10  event_name             290611 non-null  object
 11  event_type_main        290611 non-null  object
 12  service_name           290611 non-null  object
 13  region_name            290611 non-null  object
 14  city_name              290611 non-null  object
 15  curs                   290611 non-null  float64
 16  revenue_rub            290611 non-null  float64
dtypes: datetime64[ns](2), float64(4), int32(2), int8(1), object(8)
memory usage: 33.5+ MB

**Была уменьшена размерность колоноках с целочисленными данными**

In [44]:
#Смотрю названия и содержимое колонок
df.head(3)

,user_id,device_type_canonical,order_id,order_dt,order_ts,currency_code,revenue,tickets_count,days_since_prev,event_id,event_name,event_type_main,service_name,region_name,city_name,curs,revenue_rub
0,0002849b70a3ce2,mobile,4359165,2024-08-20,2024-08-20 16:08:03,rub,1521.94,4,NaN,169230,f0f7b271-04eb-4af6-bcb8-8f05cf46d6ad,театр,Край билетов,Каменевский регион,Глиногорск,18.6972,1521.94
1,0005ca5e93f2cf4,mobile,7965605,2024-07-23,2024-07-23 18:36:24,rub,289.45,2,NaN,237325,40efeb04-81b7-4135-b41f-708ff00cc64c,выставки,Мой билет,Каменевский регион,Глиногорск,18.3419,289.45
2,0005ca5e93f2cf4,mobile,7292370,2024-10-06,2024-10-06 13:56:02,rub,1258.57,4,75.0,578454,01f3fb7b-ed07-4f94-b1d3-9a2e1ee5a8ca,другое,За билетом!,Каменевский регион,Глиногорск,19.6475,1258.57

In [45]:
#Проверка на дубликаты в категориальных колонках
#Создаем список категориальных колонок

columns=['device_type_canonical', 'currency_code', 'event_type_main', 'service_name']

In [48]:
for column in columns:
    print(f"Информация о колонке '{[column]}': ")
    print(f"Количество уникальных значений: {df[column].nunique()}")
    print(f"Количество уникальных дубликатов: {df[column].duplicated().sum()}")

Информация о колонке '['device_type_canonical']':
Количество уникальных значений: 2
Количество уникальных дубликатов: 290609
Информация о колонке '['currency_code']':
Количество уникальных значений: 2
Количество уникальных дубликатов: 290609
Информация о колонке '['event_type_main']':
Количество уникальных значений: 7
Количество уникальных дубликатов: 290604
Информация о колонке '['service_name']':
Количество уникальных значений: 36
Количество уникальных дубликатов: 290575